### ISSUE TITLE
Button does not detect existing posts

### ISSUE THREAD

**Issue by go1dfish** [voat-developers/voat-buttons#3]
If a URL has already been posted to VOAT the button still asks you to submit it again.

Ideally the button would direct you to an existing post if one were available.

**Comment by serv** [comment]
The button can't really detect existing posts unfortunately. It only handles the redirecting the user to submission page part.

There's no API available to check if the link has been submitted until you actually press `Submit` in the submission page. 

And I think voat is already finding the previously posted link and redirecting you there once you press `Submit` in the submission page. 

For example, if you try to submit
`http://www.nbcnews.com/news/us-news/university-cincinnati-police-officer-indicted-murder-death-samuel-dubose-n400511` to `news` subverse, you'll be redirected to the already submitted post.

Thanks for raising the issue. I'm gonna close this one.
